#!/bin/bash
ARCHD="$(pwd)/archive"
ARCH="${ARCHD}/integrate-kit_"$(date +"%Y%m%d_%H%M%S").zip
echo "Preparing archive @ $ARCH..."
if ! [ -d $ARCHD ]; then 
   mkdir -p $ARCHD
else
   echo "Directory ${ARCHD} found! Continuing work..."
fi
zip -r $ARCH dist --include @zipinclude.lst
