#!/bin/sh
#BRANCH="fuse-ex-and-src"
BRANCH="master"
git add -A
if [[ ! -z "$1" ]]; then 
    COMMENT="$1"
else
    COMMENT="Nothing to see here. Just committing progress..."
fi
git commit -m "$COMMENT"
git push origin $BRANCH
